cookie:
  expiry_days: 30
  key: abcd
  name: aurora_app
credentials:
  usernames:
    ak9888:
      email: ak9888@srmist.edu.in
      name: arnav kumar
      password: $2b$12$t/CusPJ8HRDzK8al/mTr5OMK.meh.wqqIGZCwP2b0ENJaniDcukBW
    anubhavyadav:
      email: anubhav@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: Anubhav Yadav
      password: $2b$12$uoonWIdSMPfuNg0StCUVj.VS/ylo2vRK3bsCN7i.W4lh8Cl5E9Bu.
    drishtijaiswal:
      email: drishti@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: Drishti Jaiswal
      password: $2b$12$LfRqC5gspjgSzEcAhIg6MeKlL525SdOYiCNhwlErSOOztA1RMIAOy
    eshaansabharwal:
      email: eshaan@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: Eshaan Sabharwal
      password: $2b$12$F1mJrG7CKBy.7CM51Q0Rwe7C6b2yf9hndbv.QgO2F7x/.XS8KAhXW
    sparshjaiswal:
      email: sparsh@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: Sparsh Jaiswal
      password: $2b$12$kOE2qlBMrHN7DJbWmiTGR.ZwV3ee3ntC4tfaieOJedPb8csDb.Qfm
pre-authorized:
  emails:
  - anubhavyadavff@gmail.com
