cookie:
  expiry_days: 30
  key: abcd
  name: aurora_app
credentials:
  usernames:
    anubhavyadav:
      email: anubhavyadav77ff@gmail.com
      name: Anubhav Yadav
      password: $2b$12$6Rm6pKvgCYhr2YRbrV.6L.ii6Ws71PbpYjfluCgGPRvUj9P2mTeGG
    thenitro:
      email: nitrov99@gmail.com
      name: Ujjwal Singh
      password: $2b$12$bz3WEpRe2kykp8Hxkrp64Omh0vbSymWKkSB9zu8mZI3oK9FWexj9O
    theujjwalsingh18:
      email: theujjwalsinghh@gmail.com
      name: Ujjwal Singh
      password: $2b$12$Y6kgKE8SOw3XzJpZ3.cPmuvNnA4ffsOSzeDOy9uSmNW8/CiUculXm
    ujju99:
      email: theujjwalsinghh@gmail.com
      name: Ujjwal Singh
      password: $2b$12$8eRERbJZQ7YKntMFu/m9IOx7hyIOZZ0wt55U3i.TKyuegAZfZRqN2
